# Generated by Django 4.1.4 on 2023-01-19 16:40

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('viewflow', '0010_viewflow20'),
    ]

    operations = [
        migrations.CreateModel(
            name='HelloWorldProcess',
            fields=[
            ],
            options={
                'verbose_name': 'World Request',
                'verbose_name_plural': 'World Requests',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('viewflow.process',),
        ),
    ]
