# Generated by Django 4.1.2 on 2022-10-29 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcel', '0002_auto_20170607_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryprocess',
            name='drop_status',
            field=models.CharField(choices=[('SCF', 'Successful'), ('ERR', 'Unsuccessful')], default=None, max_length=3, null=True),
        ),
    ]
