# Generated by Django 4.1.2 on 2022-10-29 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerverificationprocess',
            name='trusted',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='reserved',
            field=models.BooleanField(null=True),
        ),
    ]
